import type { ViolationRule } from './types'

export const RULES: ViolationRule[] = [
  // ── Word Choice ──────────────────────────────────────────────────────────
  {
    id: 'overused-intensifiers',
    name: 'Overused Intensifier',
    category: 'word-choice',
    description: 'Words like "crucial," "vital," "robust," "leverage," "delve," etc. are LLM clichés that add noise.',
    tip: 'Delete it. If the sentence still makes sense, the word was never needed. If it doesn\'t, rewrite the sentence to show why it matters.',
    canRemove: true,
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.18)',
    requiresLLM: false,
  },
  {
    id: 'elevated-register',
    name: 'Elevated Register',
    category: 'word-choice',
    description: 'Using "utilize" instead of "use," "commence" instead of "start," "facilitate" instead of "help."',
    tip: 'Replace with the simpler word. "Utilize" → "use." "Commence" → "start." Elevated register performs intelligence rather than demonstrating it.',
    canRemove: false,
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.18)',
    requiresLLM: false,
  },
  {
    id: 'filler-adverbs',
    name: 'Filler Adverb',
    category: 'word-choice',
    description: '"Importantly," "essentially," "fundamentally," "ultimately," "inherently" signal importance without substantiating it.',
    tip: 'Remove it. If the sentence still works, the adverb was empty. If it doesn\'t work without it, the sentence needs to be rewritten to earn the emphasis.',
    canRemove: true,
    color: '#eab308',
    bgColor: 'rgba(234,179,8,0.18)',
    requiresLLM: false,
  },
  {
    id: 'almost-hedge',
    name: '"Almost" Hedge',
    category: 'word-choice',
    description: '"Almost always," "almost never," "almost certainly" — hedging instead of committing to the pattern.',
    tip: 'Commit. "Almost always" → "usually." Or just say "always" and defend the claim. Readers notice when you won\'t take a stance.',
    canRemove: false,
    color: '#84cc16',
    bgColor: 'rgba(132,204,22,0.18)',
    requiresLLM: false,
  },
  {
    id: 'era-opener',
    name: '"In an Era of…"',
    category: 'word-choice',
    description: 'Opening phrase that stalls before reaching the actual argument.',
    tip: 'Delete this clause entirely and start the sentence at the real point. "In an era of rapid change, companies must adapt" → "Companies must adapt."',
    canRemove: false,
    color: '#22d3ee',
    bgColor: 'rgba(34,211,238,0.15)',
    requiresLLM: false,
  },

  // ── Framing ──────────────────────────────────────────────────────────────
  {
    id: 'metaphor-crutch',
    name: 'Metaphor Crutch',
    category: 'framing',
    description: 'Predictable metaphors: "double-edged sword," "tip of the iceberg," "north star," "game-changer," etc.',
    tip: 'Either find a specific, original image from the actual subject matter, or drop the metaphor and say the thing plainly.',
    canRemove: false,
    color: '#a78bfa',
    bgColor: 'rgba(167,139,250,0.18)',
    requiresLLM: false,
  },
  {
    id: 'broader-implications',
    name: '"Broader Implications"',
    category: 'framing',
    description: 'Zooming out to claim significance without substantiation.',
    tip: 'State the implication explicitly, or cut the phrase. "This has broader implications" says nothing. What are the implications? Say them.',
    canRemove: false,
    color: '#38bdf8',
    bgColor: 'rgba(56,189,248,0.15)',
    requiresLLM: false,
  },

  // ── Sentence Structure ───────────────────────────────────────────────────
  {
    id: 'em-dash-pivot',
    name: 'Em-Dash Overuse',
    category: 'sentence-structure',
    description: 'Em-dashes used as catch-all punctuation instead of choosing the right mark.',
    tip: 'Ask what relationship this dash is expressing. A pause → comma. A list → colon. A parenthetical → parentheses. A new sentence → period. Choose the right tool.',
    canRemove: false,
    color: '#fb7185',
    bgColor: 'rgba(251,113,133,0.18)',
    requiresLLM: false,
  },
  {
    id: 'negation-pivot',
    name: 'Negation Pivot',
    category: 'sentence-structure',
    description: '"Not X, but Y" / "don\'t X, but Y" — negation followed by reframe. A hallmark LLM rhetorical structure.',
    tip: 'Rewrite as a direct positive claim. "We don\'t constrain through prohibition, but through amplification" → "We constrain through amplification." Lead with what is true, not what isn\'t.',
    canRemove: false,
    color: '#f43f5e',
    bgColor: 'rgba(244,63,94,0.15)',
    requiresLLM: false,
  },
  {
    id: 'colon-elaboration',
    name: 'Colon Elaboration',
    category: 'sentence-structure',
    description: 'Short declarative clause, colon, then longer explanation — a mechanical LLM sentence pattern.',
    tip: 'Either merge into one flowing sentence, or make two separate sentences. The colon-elaboration structure becomes predictable when used repeatedly.',
    canRemove: false,
    color: '#f472b6',
    bgColor: 'rgba(244,114,182,0.15)',
    requiresLLM: false,
  },
  {
    id: 'question-then-answer',
    name: 'Question-Then-Answer',
    category: 'sentence-structure',
    description: 'Rhetorical question immediately followed by its own answer.',
    tip: 'Delete the question and just make the statement. "What does this mean? It means X." → "This means X."',
    canRemove: false,
    color: '#34d399',
    bgColor: 'rgba(52,211,153,0.15)',
    requiresLLM: false,
  },
  {
    id: 'staccato-burst',
    name: 'Staccato Burst',
    category: 'sentence-structure',
    description: 'Three or more consecutive very short sentences at matching cadence.',
    tip: 'Vary the rhythm. Combine some of these sentences, or expand one into a full thought. Uniform short sentences feel like a list of bullet points in disguise.',
    canRemove: false,
    color: '#60a5fa',
    bgColor: 'rgba(96,165,250,0.15)',
    requiresLLM: false,
  },
  {
    id: 'hedge-stack',
    name: 'Hedge Stack',
    category: 'sentence-structure',
    description: 'Multiple hedges in one sentence: "perhaps," "arguably," "might," "could," "seemingly," etc.',
    tip: 'Pick one hedge if you need it, remove the rest. Better: commit to the claim and let the reader evaluate it. Five hedges communicate nothing.',
    canRemove: false,
    color: '#4ade80',
    bgColor: 'rgba(74,222,128,0.15)',
    requiresLLM: false,
  },
  {
    id: 'parenthetical-qualifier',
    name: 'Parenthetical Qualifier',
    category: 'sentence-structure',
    description: 'Parenthetical asides that perform nuance without changing the argument.',
    tip: 'Either make the qualification part of the main sentence (it\'s important enough to say plainly) or delete it (it wasn\'t needed).',
    canRemove: true,
    color: '#c084fc',
    bgColor: 'rgba(192,132,252,0.15)',
    requiresLLM: false,
  },
  {
    id: 'unnecessary-contrast',
    name: 'Unnecessary Contrast',
    category: 'sentence-structure',
    description: '"Whereas," "as opposed to," "unlike" used to restate what the first clause already implied.',
    tip: 'Delete the contrasting clause. If it adds information the reader didn\'t have, rewrite it as a direct statement rather than a contrast.',
    canRemove: false,
    color: '#f87171',
    bgColor: 'rgba(248,113,113,0.15)',
    requiresLLM: false,
  },

  // ── Rhetorical ───────────────────────────────────────────────────────────
  {
    id: 'important-to-note',
    name: '"It\'s Important to Note"',
    category: 'rhetorical',
    description: 'Verbal tic that precedes qualifications — tells the reader what to think before saying the thing.',
    tip: 'Delete the phrase and just say the thing. "It\'s important to note that X" → "X."',
    canRemove: false,
    color: '#fbbf24',
    bgColor: 'rgba(251,191,36,0.18)',
    requiresLLM: false,
  },
  {
    id: 'false-conclusion',
    name: 'False Conclusion',
    category: 'rhetorical',
    description: '"At the end of the day," "in conclusion," "to summarize" — high-school essay signposting.',
    tip: 'Delete the phrase. The conclusion should land through its content, not be announced. If you need to say "in conclusion," the conclusion isn\'t clear enough.',
    canRemove: false,
    color: '#e879f9',
    bgColor: 'rgba(232,121,249,0.15)',
    requiresLLM: false,
  },
  {
    id: 'connector-addiction',
    name: 'Connector Addiction',
    category: 'rhetorical',
    description: 'Every paragraph opened with a transition word: "Furthermore," "Moreover," "Additionally," etc.',
    tip: 'Delete the transition and let the ideas connect through their content. If the connection isn\'t obvious without the word, restructure — don\'t signal.',
    canRemove: false,
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.15)',
    requiresLLM: false,
  },

  // ── Structural ───────────────────────────────────────────────────────────
  {
    id: 'listicle-instinct',
    name: 'Listicle Instinct',
    category: 'structural',
    description: 'Lists with exactly 3, 5, 7, or 10 items — LLMs default to these magic numbers.',
    tip: 'Ask if this really needs a list. If the items have natural prose flow, write them as prose. If it is a list, let it have the number of items it actually has — 4, 6, 9.',
    canRemove: false,
    color: '#fb923c',
    bgColor: 'rgba(251,146,60,0.15)',
    requiresLLM: false,
  },

  // ── Sentence Structure (new) ─────────────────────────────────────────────
  {
    id: 'serves-as',
    name: '"Serves As" Dodge',
    category: 'sentence-structure',
    description: 'Replacing "is/are" with pompous alternatives: "serves as," "stands as," "acts as," "functions as."',
    tip: 'Replace with "is" or "are." The pompous substitute performs sophistication without adding meaning.',
    canRemove: false,
    color: '#818cf8',
    bgColor: 'rgba(129,140,248,0.18)',
    requiresLLM: false,
  },
  {
    id: 'negation-countdown',
    name: '"Not X. Not Y. Just Z."',
    category: 'sentence-structure',
    description: '2+ consecutive sentences starting with "Not " — building tension by negating before revealing.',
    tip: 'Cut the negations and state the positive claim directly.',
    canRemove: false,
    color: '#fb7185',
    bgColor: 'rgba(251,113,133,0.15)',
    requiresLLM: false,
  },
  {
    id: 'anaphora-abuse',
    name: 'Anaphora Abuse',
    category: 'sentence-structure',
    description: '3+ consecutive sentences starting with the same two-word opener.',
    tip: 'Vary the sentence openings. Anaphora becomes a tic when used more than twice.',
    canRemove: false,
    color: '#22d3ee',
    bgColor: 'rgba(34,211,238,0.15)',
    requiresLLM: false,
  },
  {
    id: 'gerund-litany',
    name: 'Gerund Fragment Litany',
    category: 'sentence-structure',
    description: '2+ consecutive short sentences (≤8 words) starting with a capital -ing word.',
    tip: 'Expand these into full sentences or merge them. The gerund litany is a mechanical rhythm.',
    canRemove: false,
    color: '#84cc16',
    bgColor: 'rgba(132,204,22,0.15)',
    requiresLLM: false,
  },
  {
    id: 'superficial-analysis',
    name: 'Superficial Analysis',
    category: 'sentence-structure',
    description: 'Trailing participle phrase claiming false significance: ", highlighting its importance," ", underscoring its role," etc.',
    tip: 'Cut the trailing phrase entirely. If the significance is real, make it a separate sentence with a specific claim.',
    canRemove: true,
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.15)',
    requiresLLM: false,
  },

  // ── Rhetorical (new) ─────────────────────────────────────────────────────
  {
    id: 'heres-the-kicker',
    name: '"Here\'s the Kicker"',
    category: 'rhetorical',
    description: 'False suspense transitions: "here\'s the kicker," "here\'s the thing," "here\'s where it gets interesting," etc.',
    tip: 'Delete the transition and state the point directly.',
    canRemove: true,
    color: '#d946ef',
    bgColor: 'rgba(217,70,239,0.15)',
    requiresLLM: false,
  },
  {
    id: 'pedagogical-aside',
    name: 'Pedagogical Aside',
    category: 'rhetorical',
    description: 'Teacher-mode phrases: "let\'s break this down," "let\'s unpack," "think of it as," etc.',
    tip: 'Skip the preamble and explain the thing directly. The reader doesn\'t need to be managed.',
    canRemove: false,
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.15)',
    requiresLLM: false,
  },
  {
    id: 'imagine-world',
    name: '"Imagine a World Where"',
    category: 'rhetorical',
    description: 'Opens with a futurist invitation: "Imagine a world," "Imagine if you," "Imagine what would," "Imagine a future."',
    tip: 'Start with the actual argument instead of inviting the reader to imagine it.',
    canRemove: false,
    color: '#7c3aed',
    bgColor: 'rgba(124,58,237,0.15)',
    requiresLLM: false,
  },
  {
    id: 'vague-attribution',
    name: 'Vague Attribution',
    category: 'rhetorical',
    description: 'Unnamed authority invocations: "experts argue," "studies show," "observers have noted," "research suggests," etc.',
    tip: 'Name the experts, cite the studies, or drop the claim. Vague attribution is worse than no citation.',
    canRemove: false,
    color: '#64748b',
    bgColor: 'rgba(100,116,139,0.15)',
    requiresLLM: false,
  },
  {
    id: 'despite-challenges',
    name: '"Despite Its Challenges"',
    category: 'rhetorical',
    description: 'Formula: "Despite [these/its/the] [challenges/obstacles/limitations]..." — conceding without substance.',
    tip: 'Name the specific challenge. "Despite its challenges" is a throat-clear disguised as an acknowledgment.',
    canRemove: false,
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.15)',
    requiresLLM: false,
  },

  // ── Structural (new) ─────────────────────────────────────────────────────
  {
    id: 'listicle-trench-coat',
    name: 'Listicle in a Trench Coat',
    category: 'structural',
    description: '"The first... The second... The third..." — prose disguising a list.',
    tip: 'Either use an actual list or rewrite as genuine prose. Don\'t pretend a list is an argument.',
    canRemove: false,
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.15)',
    requiresLLM: false,
  },
  {
    id: 'bold-first-bullets',
    name: 'Bold-First Bullets',
    category: 'structural',
    description: 'Markdown list items starting with a bolded phrase: "- **Term**: explanation."',
    tip: 'Either use a definition list format or integrate the bold label into prose. This is pure LLM document structure.',
    canRemove: false,
    color: '#ca8a04',
    bgColor: 'rgba(202,138,4,0.15)',
    requiresLLM: false,
  },
  {
    id: 'unicode-arrows',
    name: 'Unicode Decoration',
    category: 'structural',
    description: 'The → arrow character used in prose as a decoration or shorthand.',
    tip: 'Write out the relationship. "Input → Output" → "Input produces Output."',
    canRemove: false,
    color: '#475569',
    bgColor: 'rgba(71,85,105,0.15)',
    requiresLLM: false,
  },
  {
    id: 'dramatic-fragment',
    name: 'Dramatic Fragment',
    category: 'structural',
    description: 'A standalone paragraph with ≤4 words — used for false dramatic emphasis.',
    tip: 'Either expand it into a real sentence or absorb it into the surrounding paragraph.',
    canRemove: false,
    color: '#f43f5e',
    bgColor: 'rgba(244,63,94,0.15)',
    requiresLLM: false,
  },

  // ── Framing (new) ────────────────────────────────────────────────────────
  {
    id: 'concept-label',
    name: 'Invented Concept Label',
    category: 'framing',
    description: 'Compound noun + abstract suffix used as an invented analytical term: "the attention paradox," "the trust vacuum," "the context creep."',
    tip: 'Either explain the phenomenon in plain terms or use an established name for it.',
    canRemove: false,
    color: '#c084fc',
    bgColor: 'rgba(192,132,252,0.15)',
    requiresLLM: false,
  },

  // ── LLM-required semantic detections ─────────────────────────────────────
  {
    id: 'triple-construction',
    name: 'Triple Construction',
    category: 'sentence-structure',
    description: 'Exactly three parallel items: "X, Y, and Z" — LLMs default to threes compulsively.',
    tip: 'Break the pattern. Use two items or four. Or convert one item into its own sentence to give it more weight.',
    canRemove: false,
    color: '#a3e635',
    bgColor: 'rgba(163,230,53,0.15)',
    requiresLLM: true,
  },
  {
    id: 'throat-clearing',
    name: 'Throat-Clearing Opener',
    category: 'rhetorical',
    description: 'First paragraph that adds no information and could be deleted without any loss.',
    tip: 'Delete the whole paragraph and start at the second one. The real piece almost always begins at the second paragraph.',
    canRemove: true,
    color: '#f472b6',
    bgColor: 'rgba(244,114,182,0.15)',
    requiresLLM: true,
  },
  {
    id: 'sycophantic-frame',
    name: 'Sycophantic Frame',
    category: 'rhetorical',
    description: 'Opening that compliments the question or topic before addressing it.',
    tip: 'Delete the compliment entirely. "Great question! X is important because…" → "X is important because…"',
    canRemove: true,
    color: '#fdba74',
    bgColor: 'rgba(253,186,116,0.18)',
    requiresLLM: true,
  },
  {
    id: 'balanced-take',
    name: 'Balanced Take',
    category: 'rhetorical',
    description: 'Every argument immediately followed by a concession that softens it to nothing.',
    tip: 'Make the argument. Acknowledge genuine counterarguments separately and specifically. Don\'t reflexively soften every claim — it reads as epistemic cowardice.',
    canRemove: false,
    color: '#86efac',
    bgColor: 'rgba(134,239,172,0.15)',
    requiresLLM: true,
  },
  {
    id: 'unnecessary-elaboration',
    name: 'Unnecessary Elaboration',
    category: 'sentence-structure',
    description: 'The sentence makes its point, then keeps going to restate it.',
    tip: 'Cut at the point where the sentence was done. The restatement dilutes the original impact.',
    canRemove: false,
    color: '#fca5a5',
    bgColor: 'rgba(252,165,165,0.15)',
    requiresLLM: true,
  },
  {
    id: 'empathy-performance',
    name: 'Empathy Performance',
    category: 'rhetorical',
    description: 'Generic emotional language ("I understand this can be difficult") applicable to any topic.',
    tip: 'Delete it, or replace with something specific to this exact situation. Generic empathy is indistinguishable from no empathy.',
    canRemove: true,
    color: '#93c5fd',
    bgColor: 'rgba(147,197,253,0.15)',
    requiresLLM: true,
  },
  {
    id: 'pivot-paragraph',
    name: 'Pivot Paragraph',
    category: 'structural',
    description: 'A one-sentence paragraph containing no new information, only transition.',
    tip: 'Delete it. Attach the transition thought to either the paragraph before or after, or cut it entirely — the surrounding content should do this work.',
    canRemove: true,
    color: '#c4b5fd',
    bgColor: 'rgba(196,181,253,0.15)',
    requiresLLM: true,
  },
  {
    id: 'false-range',
    name: 'False Range',
    category: 'sentence-structure',
    description: '"From X to Y" constructions where X and Y aren\'t on a meaningful spectrum, or hollow idioms like "doesn\'t emerge from nowhere".',
    tip: 'Either show a real spectrum or cut the framing entirely.',
    canRemove: false,
    color: '#fbbf24',
    bgColor: 'rgba(251,191,36,0.15)',
    requiresLLM: false,
  },
  {
    id: 'grandiose-stakes',
    name: 'Grandiose Stakes',
    category: 'framing',
    description: 'Inflating the stakes of an ordinary argument to world-historical significance without substantiation.',
    tip: 'Scale the claim to match the evidence. If it\'s not world-historical, don\'t say so.',
    canRemove: false,
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.15)',
    requiresLLM: true,
  },
  {
    id: 'historical-analogy',
    name: 'Historical Analogy Stack',
    category: 'rhetorical',
    description: 'Rapid-fire listing of famous companies or tech revolutions to build false authority by association.',
    tip: 'Pick one analogy and develop it. A list of analogies proves nothing — it just borrows the aura of many things.',
    canRemove: false,
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.15)',
    requiresLLM: true,
  },
  {
    id: 'false-vulnerability',
    name: 'False Vulnerability',
    category: 'rhetorical',
    description: 'Performative self-awareness or simulated honesty ("I\'ll be honest," "Let\'s be real") that reads as staged rather than genuine.',
    tip: 'Real vulnerability is specific and uncomfortable. If it sounds polished, cut it.',
    canRemove: false,
    color: '#a855f7',
    bgColor: 'rgba(168,85,247,0.15)',
    requiresLLM: true,
  },

  // ── Document-level (Sonnet) ───────────────────────────────────────────────
  {
    id: 'dead-metaphor',
    name: 'Dead Metaphor',
    category: 'framing',
    description: 'The same metaphor or image recurs throughout the piece, becoming mechanical rather than intentional.',
    tip: 'Keep the instance that earns its place most and cut the rest. The same image used five times is no longer a choice.',
    canRemove: false,
    color: '#fb923c',
    bgColor: 'rgba(251,146,60,0.15)',
    requiresLLM: true,
  },
  {
    id: 'one-point-dilution',
    name: 'One-Point Dilution',
    category: 'structural',
    description: 'The same core argument restated across multiple paragraphs with different words but no new information.',
    tip: 'Find where the point was made best and cut every restatement. A strong claim once beats the same claim eight times.',
    canRemove: false,
    color: '#94a3b8',
    bgColor: 'rgba(148,163,184,0.15)',
    requiresLLM: true,
  },
  {
    id: 'fractal-summaries',
    name: 'Fractal Summaries',
    category: 'structural',
    description: 'Meta-commentary that previews or recaps content rather than delivering it: "In this section we\'ll explore...", "As we\'ve seen..."',
    tip: 'Delete the signpost and say the thing. The content should do this work.',
    canRemove: true,
    color: '#6366f1',
    bgColor: 'rgba(99,102,241,0.15)',
    requiresLLM: true,
  },
]

export const RULES_BY_ID = Object.fromEntries(RULES.map(r => [r.id, r]))
